# ==============================================================
# W11 assessment - what would the episode scheduler do on its first real run?
#
# READ ONLY. Creates nothing, changes nothing, and rolls back regardless.
#
# Historical test data is not being reconciled (it is synthetic: ~1,000
# Dispatch Cases and ~700 debt-kind tasks generated by earlier smoke tests and
# the e2e suite). What DOES matter is whether the new code copes with it
# without doing something drastic on its first run -- in particular
# Scheduled-debt-collection-episodes, which iterates every customer holding an
# unpaid invoice and has no per-run cap.
#
# Usage (from repo root):
#   Get-Content deploy\test\deploy\group-11-financial-tail\w11-assess-first-scheduler-run.py |
#     ssh -i $env:USERPROFILE\.ssh\vps_erpnext2 root@161.97.83.156
#       "docker exec -i frappe-test-backend-1 bench --site test.erpnext.am console"
# ==============================================================
import frappe
def w11_assess():
    out = []
    try:
        frappe.set_user("Administrator")
        today = frappe.utils.nowdate()
        GRACE_DAYS = 3
        unpaid = frappe.get_all(
            "Sales Invoice",
            filters={"docstatus": 1, "outstanding_amount": [">", 0]},
            fields=["customer", "name", "due_date", "outstanding_amount"],
            limit_page_length=0,
        )
        by_customer = {}
        for inv in (unpaid or []):
            c = inv.customer
            if not c:
                continue
            if c not in by_customer:
                by_customer[c] = {"outstanding": 0, "max_overdue": -99999}
            e = by_customer[c]
            e["outstanding"] = e["outstanding"] + float(inv.outstanding_amount or 0)
            if inv.due_date:
                d = frappe.utils.date_diff(today, inv.due_date)
                if d > e["max_overdue"]:
                    e["max_overdue"] = d
        would_raise = 0
        blocked_by_open = 0
        not_yet_due = 0
        over_threshold = 0
        for c in by_customer:
            info = by_customer[c]
            openq = frappe.db.count("Task", {"task_kind": "Debt Collection", "customer": c, "status": ["not in", ["Completed", "Cancelled"]]})
            if openq:
                blocked_by_open = blocked_by_open + 1
                continue
            reason = ""
            if info["max_overdue"] > GRACE_DAYS:
                reason = "overdue"
            if not reason:
                th = float(frappe.db.get_value("Customer", c, "debt_threshold_amd") or 0)
                if th > 0 and info["outstanding"] > th:
                    reason = "threshold"
                    over_threshold = over_threshold + 1
            if reason:
                would_raise = would_raise + 1
            else:
                not_yet_due = not_yet_due + 1
        out.append(("unpaid submitted invoices", str(len(unpaid or []))))
        out.append(("distinct customers owing", str(len(by_customer))))
        out.append(("already have an open episode", str(blocked_by_open)))
        out.append(("not yet due / under threshold", str(not_yet_due)))
        out.append(("WOULD RAISE on first run", str(would_raise)))
        out.append(("  of which threshold-driven", str(over_threshold)))
        out.append(("legacy open Debt Collection tasks", str(frappe.db.count("Task", {"task_kind": "Debt Collection", "status": ["not in", ["Completed", "Cancelled"]]}))))
        out.append(("legacy open Debt Closure Approvals", str(frappe.db.count("Task", {"task_kind": "Debt Closure Approval", "status": ["not in", ["Completed", "Cancelled"]]}))))
        out.append(("draft customer Payment Entries", str(frappe.db.count("Payment Entry", {"docstatus": 0, "party_type": "Customer"}))))
        out.append(("cases in Payment Pending", str(frappe.db.count("Dispatch Case", {"status": "Payment Pending"}))))
        out.append(("cases in Invoice Pending", str(frappe.db.count("Dispatch Case", {"status": "Invoice Pending"}))))
        out.append(("cases Closed", str(frappe.db.count("Dispatch Case", {"status": "Closed"}))))
    finally:
        frappe.set_user("Administrator")
        frappe.db.rollback()
    print("W11ASSESS_START")
    for k, v in out:
        print("W11ASSESS | {0:<36} | {1}".format(k, v))
    print("W11ASSESS_END")
w11_assess()
